/** app页面enum */
export enum APP_PAGE_ENUM {
  /** 店铺主页 */
  HOME = 1,
  /** 微页面 */
  FETURE = 2,
  /** tab栏的分类页 */
  CATEGORY = 3,
  /** 商品详情页	 */
  PRODUCT_DETAIL = 4,
  /** 新手指引	 */
  GUIDANCE = 5,
  /** 关于我们 */
  ABOUT_US = 6,
  /** 商品专区 */
  PRODUCT_ZOOM = 7,
  /** 消息中心 */
  MESSAGE_CENTER = 8,
  /** 掌柜中心 */
  MEMBER_CENTER = 9,
  /** 收益页面 */
  REVENUE = 10,
  /** 账户明细 */
  ACCOUNT_DETAIL = 11,
  /** 积分记录 */
  POINTER_RECORD = 12,
  /** 签到页 */
  CHECKIN = 13,
  /** 订单列表 */
  ORDER_LIST = 14,
  /** 成长值列表 */
  GROWTH_LIST = 15,
  /** 填写微信号 */
  WECHAT_CODE = 16,
  /** 邀请好友页 */
  INVITE_PAGE = 17,
  /** 直接打开链接 */
  OPEN_LINK = 18,
  /** 拼多多专区 */
  PDD_ZOOM = 19,
  /** 积分兑换记录 */
  POINTER_EXCHANGE_RECORD = 20,
  /** 积分商品详情 */
  POINTER_PRODUCT_DETAIL = 21,
  /** 购宜购优惠券商品列表 */
  COUPON_ITEM_LIST = 23,
  /** 个人资料编辑页 */
  PROFILE_EDIT = 24,
  /** 淘宝活动中转页 */
  TB_ACTIVITY_TRANS = 25,
  /** 淘宝活动直接跳转 */
  TB_ACTIVITY = 26,
  /** 商学院模块列表页	 */
  BUSSINESS_SCHOOL_LIST = 27,
  /** 商学院课程详情 */
  BUSSINESS_SCHOOL_ITEM_DETAIL = 28,
  /** tab栏商学院 */
  BUSSINESS_SCHOOL_TAB = 29,
  /** 拼多多活动直接跳转 */
  PDD_ACTIVITY = 30,
  /** 拼多多活动中转页 */
  PDD_ACTIVITY_TRANS = 31,
  /** 本地生活页 */
  LOCAL_LIFE = 32,
  /** 输入邀请码 */
  INVITE_CODE = 33,
  /** 生活服务订单 */
  LOCAL_LIFE_ORDER = 34,
  /** 自定义外链 */
  CUSTOM_LINK = 99999,
}
